<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BA-000095818" failures="1" tests="5" name="ErrorValidation Test" time="91.526" errors="0" timestamp="2023-01-26T02:29:39 EST">
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="0.884">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="0.676">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="0.728">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="0.664">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect  or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect  or password.]
at atulpracticecompany.tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="productErrorValidation" time="2.647"/>
</testsuite> <!-- ErrorValidation Test -->
