<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BA-000095818" failures="1" tests="5" name="ErrorValidation Test" time="96.996" errors="0" timestamp="2023-01-26T11:53:13 EST">
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="1.385">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="0.9">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="2.271">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="loginErrorValidation" time="1.118">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect  or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect  or password.]
at atulpracticecompany.tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:32)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="atulpracticecompany.tests.ErrorValidationTest" name="productErrorValidation" time="2.55"/>
</testsuite> <!-- ErrorValidation Test -->
